
steps:

- task: AzureAppServiceSettings@1
  displayName: 'Update slotSetting to false'
  inputs:
    azureSubscription: 'b3df1a00-1e0a-4362-823b-8329a87ce31f'
    appName: 'pipeline1111'
    resourceGroupName: 'pipeline1111_group'
    appSettings: |
      [
  {
    "name": "key2",
    "value": "valueefgh",
    "slotSetting": true
   }
      ]
